name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    
    - name: Build C# code
      run: dotnet build

    - name: Test C# code
      run: dotnet test

    - name: Build, Lint and Test typescript code
      run: | 
        cd DotnetTemplate.Web
        npm install
        npm run build
        npm run lint
        npm t

    - name: Notify
      run: curl -X POST --data-urlencode "payload={\"channel\": \"#general\", \"username\": \"webhookbot\", \"text\": \"This is posted to general and comes from a bot named webhookbot.\", \"icon_emoji\": \":ghost:\"}" https://hooks.slack.com/services/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
